(cl:defpackage camera1394-srv
  (:use )
  (:export
   "GETCAMERAREGISTERS"
   "<GETCAMERAREGISTERS-REQUEST>"
   "GETCAMERAREGISTERS-REQUEST"
   "<GETCAMERAREGISTERS-RESPONSE>"
   "GETCAMERAREGISTERS-RESPONSE"
   "SETCAMERAREGISTERS"
   "<SETCAMERAREGISTERS-REQUEST>"
   "SETCAMERAREGISTERS-REQUEST"
   "<SETCAMERAREGISTERS-RESPONSE>"
   "SETCAMERAREGISTERS-RESPONSE"
  ))

