/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/dhruva/Documents/mlab/autonomous-racing/pennARC_ws/src/camera1394/srv/GetCameraRegisters.srv
 *
 */


#ifndef CAMERA1394_MESSAGE_GETCAMERAREGISTERS_H
#define CAMERA1394_MESSAGE_GETCAMERAREGISTERS_H

#include <ros/service_traits.h>


#include <camera1394/GetCameraRegistersRequest.h>
#include <camera1394/GetCameraRegistersResponse.h>


namespace camera1394
{

struct GetCameraRegisters
{

typedef GetCameraRegistersRequest Request;
typedef GetCameraRegistersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCameraRegisters
} // namespace camera1394


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera1394::GetCameraRegisters > {
  static const char* value()
  {
    return "9597d397bc64c4c4fcaf24bbb15f0256";
  }

  static const char* value(const ::camera1394::GetCameraRegisters&) { return value(); }
};

template<>
struct DataType< ::camera1394::GetCameraRegisters > {
  static const char* value()
  {
    return "camera1394/GetCameraRegisters";
  }

  static const char* value(const ::camera1394::GetCameraRegisters&) { return value(); }
};


// service_traits::MD5Sum< ::camera1394::GetCameraRegistersRequest> should match 
// service_traits::MD5Sum< ::camera1394::GetCameraRegisters > 
template<>
struct MD5Sum< ::camera1394::GetCameraRegistersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera1394::GetCameraRegisters >::value();
  }
  static const char* value(const ::camera1394::GetCameraRegistersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera1394::GetCameraRegistersRequest> should match 
// service_traits::DataType< ::camera1394::GetCameraRegisters > 
template<>
struct DataType< ::camera1394::GetCameraRegistersRequest>
{
  static const char* value()
  {
    return DataType< ::camera1394::GetCameraRegisters >::value();
  }
  static const char* value(const ::camera1394::GetCameraRegistersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera1394::GetCameraRegistersResponse> should match 
// service_traits::MD5Sum< ::camera1394::GetCameraRegisters > 
template<>
struct MD5Sum< ::camera1394::GetCameraRegistersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera1394::GetCameraRegisters >::value();
  }
  static const char* value(const ::camera1394::GetCameraRegistersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera1394::GetCameraRegistersResponse> should match 
// service_traits::DataType< ::camera1394::GetCameraRegisters > 
template<>
struct DataType< ::camera1394::GetCameraRegistersResponse>
{
  static const char* value()
  {
    return DataType< ::camera1394::GetCameraRegisters >::value();
  }
  static const char* value(const ::camera1394::GetCameraRegistersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA1394_MESSAGE_GETCAMERAREGISTERS_H
