// Generated by gencpp from file camera1394/SetCameraRegisters.msg
// DO NOT EDIT!


#ifndef CAMERA1394_MESSAGE_SETCAMERAREGISTERS_H
#define CAMERA1394_MESSAGE_SETCAMERAREGISTERS_H

#include <ros/service_traits.h>


#include <camera1394/SetCameraRegistersRequest.h>
#include <camera1394/SetCameraRegistersResponse.h>


namespace camera1394
{

struct SetCameraRegisters
{

typedef SetCameraRegistersRequest Request;
typedef SetCameraRegistersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCameraRegisters
} // namespace camera1394


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera1394::SetCameraRegisters > {
  static const char* value()
  {
    return "703211788a5d6f08f820dfb1792ab51c";
  }

  static const char* value(const ::camera1394::SetCameraRegisters&) { return value(); }
};

template<>
struct DataType< ::camera1394::SetCameraRegisters > {
  static const char* value()
  {
    return "camera1394/SetCameraRegisters";
  }

  static const char* value(const ::camera1394::SetCameraRegisters&) { return value(); }
};


// service_traits::MD5Sum< ::camera1394::SetCameraRegistersRequest> should match 
// service_traits::MD5Sum< ::camera1394::SetCameraRegisters > 
template<>
struct MD5Sum< ::camera1394::SetCameraRegistersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera1394::SetCameraRegisters >::value();
  }
  static const char* value(const ::camera1394::SetCameraRegistersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera1394::SetCameraRegistersRequest> should match 
// service_traits::DataType< ::camera1394::SetCameraRegisters > 
template<>
struct DataType< ::camera1394::SetCameraRegistersRequest>
{
  static const char* value()
  {
    return DataType< ::camera1394::SetCameraRegisters >::value();
  }
  static const char* value(const ::camera1394::SetCameraRegistersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera1394::SetCameraRegistersResponse> should match 
// service_traits::MD5Sum< ::camera1394::SetCameraRegisters > 
template<>
struct MD5Sum< ::camera1394::SetCameraRegistersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera1394::SetCameraRegisters >::value();
  }
  static const char* value(const ::camera1394::SetCameraRegistersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera1394::SetCameraRegistersResponse> should match 
// service_traits::DataType< ::camera1394::SetCameraRegisters > 
template<>
struct DataType< ::camera1394::SetCameraRegistersResponse>
{
  static const char* value()
  {
    return DataType< ::camera1394::SetCameraRegisters >::value();
  }
  static const char* value(const ::camera1394::SetCameraRegistersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA1394_MESSAGE_SETCAMERAREGISTERS_H
