// Generated by gencpp from file beginner_tutorials/driveMessage.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_DRIVEMESSAGE_H
#define BEGINNER_TUTORIALS_MESSAGE_DRIVEMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct driveMessage_
{
  typedef driveMessage_<ContainerAllocator> Type;

  driveMessage_()
    : steering(0)
    , throttle(0)  {
    }
  driveMessage_(const ContainerAllocator& _alloc)
    : steering(0)
    , throttle(0)  {
    }



   typedef int16_t _steering_type;
  _steering_type steering;

   typedef int16_t _throttle_type;
  _throttle_type throttle;




  typedef boost::shared_ptr< ::beginner_tutorials::driveMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::driveMessage_<ContainerAllocator> const> ConstPtr;

}; // struct driveMessage_

typedef ::beginner_tutorials::driveMessage_<std::allocator<void> > driveMessage;

typedef boost::shared_ptr< ::beginner_tutorials::driveMessage > driveMessagePtr;
typedef boost::shared_ptr< ::beginner_tutorials::driveMessage const> driveMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::driveMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::driveMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/pari/pennARC_ws/src/beginner_tutorials/msg', '/home/pari/pennARC_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'custom_messages': ['/home/pari/pennARC_ws/src/custom_messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::driveMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::driveMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::driveMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::driveMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::driveMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::driveMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::driveMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4dd5817de7802d91e66008f92eca79e";
  }

  static const char* value(const ::beginner_tutorials::driveMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4dd5817de7802d9ULL;
  static const uint64_t static_value2 = 0x1e66008f92eca79eULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::driveMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/driveMessage";
  }

  static const char* value(const ::beginner_tutorials::driveMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::driveMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 steering\n\
int16 throttle\n\
";
  }

  static const char* value(const ::beginner_tutorials::driveMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::driveMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steering);
      stream.next(m.throttle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct driveMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::driveMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::driveMessage_<ContainerAllocator>& v)
  {
    s << indent << "steering: ";
    Printer<int16_t>::stream(s, indent + "  ", v.steering);
    s << indent << "throttle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.throttle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_DRIVEMESSAGE_H
